export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_HAS_ERROR = 'PRODUCTS_HAS_ERROR';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const MINUS_PRODUCT_QTY_FROM_STORE = 'MINUS_PRODUCT_QTY_FROM_STORE';